### PR TITLE
feat(refs): Add possibility to link optional ref_type 

### PR DESCRIPTION
**Pull request by joli-sys**

### CODE REVIEW

**Comment by saidsef** [comment]
Hi @joli-sys , thanks for contributing.

Could you please update examples/complete test: https://github.com/cookielab/terraform-aws-gitlab-oidc/blob/main/examples/complete/variables.tf

To test, you can run:
```shell
pre-commit run -a 
```
> you'll need to [install pre-commit](https://pre-commit.com/)

**Comment by joli-sys** [comment]
> Hi @joli-sys , thanks for contributing.
> 
> Could you please update examples/complete test: https://github.com/cookielab/terraform-aws-gitlab-oidc/blob/main/examples/complete/variables.tf
> 
> To test, you can run:
> 
> ```shell
> pre-commit run -a 
> ```
> 
> > you'll need to [install pre-commit](https://pre-commit.com/)

I updated all docs, tfvars etc...

**Comment by saidsef** [comment]
Thanks @joli-sys. All looks good, I'm going to merge this PR.

The pipeline failed due to external users not having access to secrets, so that is unrelated to this PR.

**Review by saidsef — APPROVED** [review]

**Comment by saidsef** [comment]
I'm going to bump tag version to v2.2.0

**Pull request merged**
